version: '2.2.0.{build}'
image: Visual Studio 2017
build:
  project: src/
  publish_nuget: true
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./src --verbosity m
  - cmd: nuget restore .\src 
build_script:
  - cmd: dotnet pack ./src/System.Net.IPNetwork
test_script:
  - cmd: dotnet test ./src/System.Net.IPNetwork.TestProject.NetCore/System.Net.IPNetwork.TestProject.NetCore.csproj
  - vstest.console /logger:Appveyor c:\Projects\ipnetwork\src\System.Net.IPNetwork.TestProject.NetCore\bin\Debug\netcoreapp2.0\System.Net.IPNetwork.TestProject.NetCore.dll
deploy: off
